#!/usr/bin/env bash
# ============================================================================
# common.sh — Shared functions for BMAD hook scripts
#
# Path model (bare repo layout):
#   PROJECT_ROOT     = ProjectAlpha/          (bare repo parent, worktree siblings)
#   BARE_REPO        = ProjectAlpha/.bare/    (git object database)
#   MAIN_WORKTREE    = ProjectAlpha/main/     (main branch, hooks, BMAD artifacts)
#   Feature worktrees = ProjectAlpha/{key}/   (siblings of main/)
#
# When running inside a worktree (hooks), CLAUDE_PROJECT_DIR points to
# the worktree directory (e.g. ProjectAlpha/main/ or ProjectAlpha/REMS-101/).
# We derive PROJECT_ROOT as its parent.
# ============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------
# CLAUDE_PROJECT_DIR is set by Claude Code to its working directory.
# For hooks running in a worktree, this is the worktree path.
# PROJECT_ROOT is one level up (the bare repo parent).
WORKTREE_DIR="${CLAUDE_PROJECT_DIR:-.}"
PROJECT_ROOT="$(cd "${WORKTREE_DIR}/.." 2>/dev/null && pwd || dirname "$(pwd)")"

# Main worktree — where BMAD artifacts and sprint file live
MAIN_WORKTREE="${PROJECT_ROOT}/main"

# Ticket-aware path resolution
# When BMAD_TICKET is set (e.g., RZP-1029), artifacts are namespaced:
#   _bmad-output/RZP-1029/implementation-artifacts/sprint-status.yaml
#   _bmad-output/RZP-1029/implementation-artifacts/pipeline-status.yaml
# Baseline docs always live at: _bmad-output/planning-artifacts/
BMAD_TICKET="${BMAD_TICKET:-}"
if [[ -n "${BMAD_TICKET}" ]]; then
  BMAD_ARTIFACTS_BASE="${MAIN_WORKTREE}/_bmad-output/${BMAD_TICKET}/implementation-artifacts"
  BMAD_PLANNING_BASE="${MAIN_WORKTREE}/_bmad-output/${BMAD_TICKET}/planning-artifacts"
else
  BMAD_ARTIFACTS_BASE="${MAIN_WORKTREE}/_bmad-output/implementation-artifacts"
  BMAD_PLANNING_BASE="${MAIN_WORKTREE}/_bmad-output/planning-artifacts"
fi
BMAD_BASELINE_BASE="${MAIN_WORKTREE}/_bmad-output/planning-artifacts"

# Pipeline status (generated by bmad-converter.py from BMAD's sprint-status.yaml)
SPRINT_FILE="${BMAD_ARTIFACTS_BASE}/pipeline-status.yaml"
BMAD_SPRINT_FILE="${BMAD_ARTIFACTS_BASE}/sprint-status.yaml"
CONVERTER="${PROJECT_ROOT}/bmad-converter.py"
PROGRESS_LOG="${BMAD_ARTIFACTS_BASE}/progress.log"
LOG_DIR="${BMAD_ARTIFACTS_BASE}/logs"

# Phase state tracks the current story/phase for this session
PHASE_STATE_FILE="${WORKTREE_DIR}/.claude/.phase-state"

# ---------------------------------------------------------------------------
# Model tiers — Opus for reasoning-heavy, Sonnet for implementation
# ---------------------------------------------------------------------------
MODEL_CREATE="${BMAD_MODEL_CREATE:-claude-opus-4-6}"
MODEL_DEV="${BMAD_MODEL_DEV:-claude-sonnet-4-6}"
MODEL_REVIEW="${BMAD_MODEL_REVIEW:-claude-opus-4-6}"

model_for_phase() {
  local phase="$1"
  case "${phase}" in
    create-story) echo "${MODEL_CREATE}" ;;
    dev-story)    echo "${MODEL_DEV}" ;;
    code-review)  echo "${MODEL_REVIEW}" ;;
    *)            echo "${MODEL_DEV}" ;;
  esac
}

# BMAD workflow locations (searched in order, relative to main worktree)
BMAD_COMMAND_DIRS=(
  "${MAIN_WORKTREE}/_bmad/bmm/workflows/4-implementation"
  "${MAIN_WORKTREE}/.claude/commands"
  "${MAIN_WORKTREE}/.claude/skills"
  "${HOME}/.claude/commands"
)

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
log() {
  local level="$1"; shift
  mkdir -p "$(dirname "${PROGRESS_LOG}")" 2>/dev/null || true
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] [${level}] $*" >> "${PROGRESS_LOG}" 2>/dev/null || true
}

log_info()  { log "INFO"  "$@"; }
log_warn()  { log "WARN"  "$@"; }
log_error() { log "ERROR" "$@"; }

# ---------------------------------------------------------------------------
# Session exhaustion detection and retry
# ---------------------------------------------------------------------------
EXHAUSTION_POLL_INTERVAL="${BMAD_EXHAUSTION_POLL_INTERVAL:-300}"  # 5 min default

is_exhaustion_error() {
  local output="$1"
  echo "${output}" | grep -qiE \
    "usage limit|rate limit|quota exceeded|too many requests|try again later|plan limit|claude\.ai/upgrade|overloaded|529|resource_exhausted|capacity|throttl"
}

run_claude_with_retry() {
  # Usage: run_claude_with_retry <label> <claude args...>
  local label="$1"; shift
  local attempt=1
  local output exit_code

  while true; do
    log_info "Claude session [${label}] attempt ${attempt}"

    output=$(claude "$@" 2>&1) || true
    exit_code=${PIPESTATUS[0]:-$?}

    if [[ ${exit_code} -eq 0 ]]; then
      echo "${output}"
      return 0
    fi

    if is_exhaustion_error "${output}"; then
      local now minutes_past seconds_until_reset
      now=$(date +%s)
      minutes_past=$(date +%M | sed 's/^0//')
      seconds_until_reset=$(( (60 - ${minutes_past:-0}) * 60 - $(date +%S | sed 's/^0//') ))
      [[ ${seconds_until_reset} -lt 30 ]] && seconds_until_reset=$(( seconds_until_reset + 3600 ))

      local reset_time
      reset_time=$(date -d "@$(( now + seconds_until_reset ))" "+%H:%M" 2>/dev/null || echo "~$(( seconds_until_reset / 60 ))m")

      log_warn "EXHAUSTION [${label}] attempt ${attempt} — waiting until ~${reset_time} (${seconds_until_reset}s)"

      # Write sentinel for monitoring
      local sentinel="${WORKTREE_DIR:-.}/.claude/.exhaustion-wait"
      echo "since=$(date -u +%Y-%m-%dT%H:%M:%SZ) reset=~${reset_time}" > "${sentinel}" 2>/dev/null || true

      while true; do
        sleep "${EXHAUSTION_POLL_INTERVAL}"
        local now_check
        now_check=$(date +%s)
        if [[ ${now_check} -ge $(( now + seconds_until_reset )) ]]; then
          log_info "EXHAUSTION [${label}] reset window passed — retrying"
          break
        fi
        local remaining=$(( now + seconds_until_reset - now_check ))
        log_info "EXHAUSTION [${label}] still waiting (~${remaining}s remaining)"
      done

      rm -f "${sentinel}" 2>/dev/null || true
      attempt=$(( attempt + 1 ))
      continue
    fi

    # Non-exhaustion failure — return immediately
    echo "${output}"
    log_warn "Claude session [${label}] failed (exit ${exit_code}, not exhaustion)"
    return ${exit_code}
  done
}

# ---------------------------------------------------------------------------
# Sprint status helpers
# ---------------------------------------------------------------------------
get_current_story_key() {
  if [[ -f "${PHASE_STATE_FILE}" ]]; then
    grep '^STORY_KEY=' "${PHASE_STATE_FILE}" | cut -d= -f2
  fi
}

get_current_phase() {
  if [[ -f "${PHASE_STATE_FILE}" ]]; then
    grep '^PHASE=' "${PHASE_STATE_FILE}" | cut -d= -f2
  fi
}

get_current_factory_mode() {
  # Read from phase state file first, then env var, then default
  if [[ -f "${PHASE_STATE_FILE}" ]]; then
    local from_file
    from_file=$(grep '^FACTORY_MODE=' "${PHASE_STATE_FILE}" 2>/dev/null | cut -d= -f2)
    if [[ -n "${from_file}" ]]; then
      echo "${from_file}"
      return
    fi
  fi
  echo "${BMAD_FACTORY_MODE:-legacy}"
}

get_story_status() {
  local key="$1"
  [[ -f "${SPRINT_FILE}" ]] || { echo "unknown"; return; }
  awk -v key="$key" '
    /^[[:space:]]*- key:/ { found = ($NF == key) }
    found && /^[[:space:]]*status:/ { gsub(/^[[:space:]]*status:[[:space:]]*/, ""); print; exit }
  ' "${SPRINT_FILE}"
}

get_story_title() {
  local key="$1"
  [[ -f "${SPRINT_FILE}" ]] || { echo "unknown"; return; }
  awk -v key="$key" '
    /^[[:space:]]*- key:/ { found = ($NF == key) }
    found && /^[[:space:]]*title:/ { gsub(/^[[:space:]]*title:[[:space:]]*/, ""); print; exit }
  ' "${SPRINT_FILE}"
}

next_ready_story() {
  [[ -f "${SPRINT_FILE}" ]] || return 1
  awk '
    /^[[:space:]]*- key:/ { key = $NF }
    /^[[:space:]]*status:[[:space:]]*ready-for-dev/ { print key; exit }
  ' "${SPRINT_FILE}"
}

update_story_status() {
  local key="$1"
  local new_status="$2"
  [[ -f "${SPRINT_FILE}" ]] || { log_error "Sprint file not found"; return 1; }
  python3 -c "
import re
key, new_status = '${key}', '${new_status}'
with open('${SPRINT_FILE}', 'r') as f:
    lines = f.readlines()
found_key = False
for i, line in enumerate(lines):
    if re.match(r'\s*- key:\s*' + re.escape(key), line):
        found_key = True
    elif found_key and re.match(r'\s*status:\s*', line):
        indent = len(line) - len(line.lstrip())
        lines[i] = ' ' * indent + 'status: ' + new_status + '\n'
        break
with open('${SPRINT_FILE}', 'w') as f:
    f.writelines(lines)
" 2>/dev/null
  log_info "Story ${key} status → ${new_status}"
  # Sync status back to BMAD format
  if [[ -f "${CONVERTER}" ]]; then
    python3 "${CONVERTER}" sync-back "${PROJECT_ROOT}" 2>/dev/null || true
  fi
}

update_story_deps() {
  # Update depends_on for a story in pipeline-status.yaml
  local key="$1"
  local deps="$2"  # comma-separated: "1-1,1-2" or "none"
  if [[ -f "${CONVERTER}" ]]; then
    python3 "${CONVERTER}" update-deps "${key}" "${deps}" "${PROJECT_ROOT}" 2>/dev/null || true
    log_info "Story ${key} deps → ${deps}"
  fi
}

get_story_slug() {
  # Get the BMAD slug for a story key (e.g. "1-1" → "1-1-project-scaffolding")
  local key="$1"
  [[ -f "${SPRINT_FILE}" ]] || return
  python3 -c "
import yaml
with open('${SPRINT_FILE}') as f:
    data = yaml.safe_load(f)
for s in data.get('stories', []):
    if s.get('key') == '${key}':
        print(s.get('slug', ''))
        break
" 2>/dev/null || true
}

set_phase_state() {
  local story_key="$1"
  local phase="$2"
  local factory_mode="${3:-}"
  # Preserve factory mode: explicit arg > env var > existing file > legacy
  if [[ -z "${factory_mode}" ]]; then
    factory_mode="${BMAD_FACTORY_MODE:-}"
  fi
  if [[ -z "${factory_mode}" && -f "${PHASE_STATE_FILE}" ]]; then
    factory_mode=$(grep '^FACTORY_MODE=' "${PHASE_STATE_FILE}" | cut -d= -f2)
  fi
  factory_mode="${factory_mode:-legacy}"
  mkdir -p "$(dirname "${PHASE_STATE_FILE}")"
  cat > "${PHASE_STATE_FILE}" <<EOF
STORY_KEY=${story_key}
PHASE=${phase}
FACTORY_MODE=${factory_mode}
UPDATED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
}

# ---------------------------------------------------------------------------
# Dependency resolution
# ---------------------------------------------------------------------------
get_story_dependencies() {
  local key="$1"
  [[ -f "${SPRINT_FILE}" ]] || return
  python3 -c "
import yaml
with open('${SPRINT_FILE}') as f:
    data = yaml.safe_load(f)
for s in data.get('stories', []):
    if s.get('key') == '${key}':
        deps = s.get('depends_on', [])
        if deps:
            print(' '.join(deps))
        break
" 2>/dev/null || true
}

deps_satisfied() {
  local key="$1"
  local deps
  deps=$(get_story_dependencies "${key}")
  [[ -z "${deps}" ]] && return 0
  for dep in ${deps}; do
    local dep_status
    dep_status=$(get_story_status "${dep}")
    [[ "${dep_status}" != "done" ]] && return 1
  done
  return 0
}

get_all_stories() {
  [[ -f "${SPRINT_FILE}" ]] || return
  awk '/^[[:space:]]*- key:/ { print $NF }' "${SPRINT_FILE}"
}

get_stories_by_status() {
  local status="$1"
  [[ -f "${SPRINT_FILE}" ]] || return
  awk -v s="${status}" '
    /^[[:space:]]*- key:/ { key = $NF }
    /^[[:space:]]*status:/ {
      gsub(/^[[:space:]]*status:[[:space:]]*/, "")
      if ($0 == s) print key
    }
  ' "${SPRINT_FILE}"
}

get_eligible_stories() {
  local created
  created=$(get_stories_by_status "story-created")
  [[ -z "${created}" ]] && return
  while IFS= read -r key; do
    deps_satisfied "${key}" && echo "${key}"
  done <<< "${created}"
}

get_story_priority() {
  local key="$1"
  [[ -f "${SPRINT_FILE}" ]] || { echo "999"; return; }
  awk -v key="$key" '
    /^[[:space:]]*- key:/ { found = ($NF == key) }
    found && /^[[:space:]]*priority:/ { gsub(/^[[:space:]]*priority:[[:space:]]*/, ""); print; exit }
  ' "${SPRINT_FILE}"
}

# ---------------------------------------------------------------------------
# Epic-level helpers (for retrospective gating)
# ---------------------------------------------------------------------------
get_all_epics() {
  # Returns unique epic identifiers (e.g., "epic-1 epic-2 epic-3")
  [[ -f "${SPRINT_FILE}" ]] || return
  awk '
    /^[[:space:]]*epic:/ {
      gsub(/^[[:space:]]*epic:[[:space:]]*/, "")
      epics[$0] = 1
    }
    END { for (e in epics) print e }
  ' "${SPRINT_FILE}" | sort
}

get_epic_number() {
  # Extract number from "epic-1" → "1"
  local epic="$1"
  echo "${epic}" | sed 's/epic-//'
}

get_stories_for_epic() {
  # Returns all story keys belonging to an epic
  local epic="$1"
  [[ -f "${SPRINT_FILE}" ]] || return
  awk -v epic="${epic}" '
    /^[[:space:]]*- key:/ { key = $NF }
    /^[[:space:]]*epic:/ {
      gsub(/^[[:space:]]*epic:[[:space:]]*/, "")
      if ($0 == epic) print key
    }
  ' "${SPRINT_FILE}"
}

is_epic_complete() {
  # Returns 0 if ALL stories in the epic are "done"
  local epic="$1"
  local stories
  stories=$(get_stories_for_epic "${epic}")
  [[ -z "${stories}" ]] && return 1
  while IFS= read -r key; do
    local status
    status=$(get_story_status "${key}")
    [[ "${status}" != "done" ]] && return 1
  done <<< "${stories}"
  return 0
}

get_retro_status() {
  # Check retrospective status from BMAD sprint-status.yaml
  local epic="$1"
  local epic_num
  epic_num=$(get_epic_number "${epic}")
  [[ -f "${BMAD_SPRINT_FILE}" ]] || { echo "unknown"; return; }
  python3 -c "
import yaml
with open('${BMAD_SPRINT_FILE}') as f:
    data = yaml.safe_load(f)
ds = data.get('development_status', {})
print(ds.get('epic-${epic_num}-retrospective', 'optional'))
" 2>/dev/null || echo "unknown"
}

update_retro_status() {
  local epic="$1"
  local new_status="$2"
  local epic_num
  epic_num=$(get_epic_number "${epic}")
  [[ -f "${BMAD_SPRINT_FILE}" ]] || return 1
  python3 -c "
import re
epic_num = '${epic_num}'
new_status = '${new_status}'
retro_key = f'epic-{epic_num}-retrospective'
with open('${BMAD_SPRINT_FILE}', 'r') as f:
    lines = f.readlines()
found = False
for i, line in enumerate(lines):
    stripped = line.strip()
    if stripped.startswith(retro_key + ':'):
        indent = len(line) - len(line.lstrip())
        lines[i] = ' ' * indent + retro_key + ': ' + new_status + '\n'
        found = True
        break
if found:
    with open('${BMAD_SPRINT_FILE}', 'w') as f:
        f.writelines(lines)
" 2>/dev/null
  log_info "Epic ${epic} retrospective → ${new_status}"
}

needs_retrospective() {
  # Returns 0 if epic is complete but retro is not done
  local epic="$1"
  is_epic_complete "${epic}" || return 1
  local retro_status
  retro_status=$(get_retro_status "${epic}")
  [[ "${retro_status}" != "done" ]]
}

epics_needing_retro() {
  # Returns list of epics that are complete but need retrospective
  local epics
  epics=$(get_all_epics)
  [[ -z "${epics}" ]] && return
  while IFS= read -r epic; do
    needs_retrospective "${epic}" && echo "${epic}"
  done <<< "${epics}"
}

is_retro_gate_clear() {
  # Returns 0 if no completed epics are waiting for retrospective
  # Used to gate factory from starting next epic's stories
  local waiting
  waiting=$(epics_needing_retro)
  [[ -z "${waiting}" ]]
}

build_dependency_graph() {
  python3 -c "
import yaml
with open('${SPRINT_FILE}') as f:
    data = yaml.safe_load(f)
stories = data.get('stories', [])
print('Dependency Graph:')
print('=' * 50)
for s in stories:
    key = s.get('key', '?')
    status = s.get('status', '?')
    deps = s.get('depends_on', [])
    dep_str = ', '.join(deps) if deps else '(none)'
    marker = '✓' if status == 'done' else '○' if status == 'story-created' else '·'
    print(f'  {marker} {key} [{status}] → depends on: {dep_str}')
print('=' * 50)
" 2>/dev/null || echo "(dependency graph unavailable — install PyYAML)"
}

# ---------------------------------------------------------------------------
# Worktree helpers (bare repo layout — worktrees are siblings of main/)
# ---------------------------------------------------------------------------
worktree_path() {
  local story_key="$1"
  echo "${PROJECT_ROOT}/${story_key}"
}

worktree_exists() {
  local story_key="$1"
  [[ -d "$(worktree_path "${story_key}")" ]]
}

worktree_create() {
  local story_key="$1"
  local base_branch="${2:-main}"
  local branch_name="feature/${story_key}"
  local wt_path
  wt_path="$(worktree_path "${story_key}")"

  if worktree_exists "${story_key}"; then
    log_info "Worktree exists: ${wt_path}"
    return 0
  fi

  # Run git from PROJECT_ROOT where .git pointer lives
  if git -C "${PROJECT_ROOT}" rev-parse --verify "${branch_name}" &>/dev/null; then
    git -C "${PROJECT_ROOT}" worktree add "${wt_path}" "${branch_name}" 2>/dev/null
    log_info "Worktree from existing branch: ${branch_name} → ${wt_path}"
  else
    git -C "${PROJECT_ROOT}" worktree add -b "${branch_name}" "${wt_path}" "${base_branch}" 2>/dev/null
    log_info "Worktree with new branch: ${branch_name} → ${wt_path}"
  fi
}

worktree_remove() {
  local story_key="$1"
  local wt_path
  wt_path="$(worktree_path "${story_key}")"
  if worktree_exists "${story_key}"; then
    git -C "${PROJECT_ROOT}" worktree remove "${wt_path}" --force 2>/dev/null || true
    log_info "Worktree removed: ${wt_path}"
  fi
}

# ---------------------------------------------------------------------------
# Git helpers (worktree-aware)
# ---------------------------------------------------------------------------
git_in_worktree() {
  local story_key
  story_key="$(get_current_story_key)"
  local wt_path
  wt_path="$(worktree_path "${story_key}")"
  if [[ -d "${wt_path}" ]]; then
    git -C "${wt_path}" "$@"
  else
    git -C "${WORKTREE_DIR}" "$@"
  fi
}

git_wip_commit() {
  local story_key="$1"
  local phase="$2"
  git_in_worktree add -A 2>/dev/null || true
  git_in_worktree diff --cached --quiet 2>/dev/null && return 0
  git_in_worktree commit -m "wip(${story_key}): ${phase}" --no-verify 2>/dev/null || true
  log_info "WIP commit: ${story_key} [${phase}]"
}

git_final_commit() {
  local story_key="$1"
  local title="$2"
  git_in_worktree add -A 2>/dev/null || true
  git_in_worktree diff --cached --quiet 2>/dev/null && return 0
  git_in_worktree commit -m "feat(${story_key}): ${title}" --no-verify 2>/dev/null || true
  log_info "Final commit: feat(${story_key}): ${title}"
}

# ---------------------------------------------------------------------------
# Read hook input from stdin
# ---------------------------------------------------------------------------
read_hook_input() {
  cat
}

# ---------------------------------------------------------------------------
# BMAD command/template lookup
# ---------------------------------------------------------------------------
find_bmad_file() {
  local name="$1"
  for dir in "${BMAD_COMMAND_DIRS[@]}"; do
    for ext in ".md" ".txt" ""; do
      [[ -f "${dir}/${name}${ext}" ]] && { echo "${dir}/${name}${ext}"; return 0; }
    done
  done
  return 1
}
